language:
  minimal

services:
  docker

script:
  make build

deploy:
  provider: script
  script: make deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH != *-alpha

notifications:
  slack:
    secure: gJ6TcSdBnLWbGSk7weXKYkVuAO255ZPRUxZFAOQbUnWNxKRfGbSirXUXPggX2V4GrCZC+Cqh65Tiltwmx8obB9NLwhIlGg1X3S4cnEuM2MVjUSfS1VwqU0fr0z/8AaoxDgP/lChw2qtlw9eXBTiZp7vTKpUzknVlEX5XrZX6sYbQ8X2eLSfBLcS04XxT9iDakrwL6MG3kJzNHHzm02zDtTXgse4qojgbPM8NZlfGcBy6jdrkfsxY/0aumIVjEuJZ3kmDBCPrjbIHkKgbq8swK/pBRpgiUrkReJGocyKOB/JjhiVWaWOqAmKeHBg3fBS39rtQ5aMeW9bm0OORC7hpqMCHiHB58JLsa8bJhpQt94Fh+YEmaQFp9LpyVyBdY2w5x8Yf+dGom49drAXOA3Kpvdx7Ni8h9u6pL5UovU1MCwpC+1EPE2pWtfUiuHZqaLj38mNSc+75RkozF9zvQEoNK5v7wmL/rfn4jnC84Rzo0ZsKxHiym5X8fIRtT+SzE9dbp24qRCdlIdZmsIpx1CEsuQLeCb1Ao8AJPlMCuW467LUd/nv/AinqNivQAzKcDAPsTrXcUXUcLgLWzmNWZiOLVIi6Rnb1N+aMZnEgLxVRIzuisBfKhx/I9rsHYQA6QUp9ze/GdgB2XmHXh+nQLBTAw7r6a5g7i1169rWGeLUl1XI=
